import Headers from "./admin/_components/Header";
import './_styles/globals.css';

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Headers />
        {children}
      </body>
    </html>
  );
}


